import { useCallback, useEffect, useRef, useState } from 'react';
import type { Dispatch, SetStateAction } from 'react';
import { ActivityIndicator, Alert, FlatList, Modal, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { exportarTarifarioJSON, importarTarifarioJSON, reemplazarTarifarioJSON } from '@/services/respaldoService';
import { actualizarServicio,buscarServicios,crearServicio,eliminarServicio,listarServicios,obtenerCategorias } from '@/services/tarifarioService';
import { agregarSeleccionTarifario } from '@/services/orderDraftStore';
import type { Servicio } from '@/types/tarifario.types';

const money=(n:number)=>new Intl.NumberFormat('es-CU',{style:'currency',currency:'CUP',maximumFractionDigits:2}).format(n||0);
const vacio=()=>({id:null as number|null,codigoServicio:'',nombreServicio:'',categoria:'',precioBase:'0',unidad:'',tiempoEstimado:'',cantidadTecnicos:'1'});

export default function TarifarioScreen(){
 const tapTimer=useRef<ReturnType<typeof setTimeout> | null>(null); const theme=useTheme(); const [texto,setTexto]=useState(''); const [categoria,setCategoria]=useState<string|null>(null); const [categorias,setCategorias]=useState<{categoria:string;total:number}[]>([]); const [servicios,setServicios]=useState<Servicio[]>([]); const [selected,setSelected]=useState<Servicio[]>([]); const [accion,setAccion]=useState<Servicio|null>(null); const [form,setForm]=useState(vacio()); const [formOpen,setFormOpen]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const lastTap=useRef<{id:number;at:number}>({id:-1,at:0});
 const cargarCategorias=useCallback(()=>{obtenerCategorias().then(setCategorias).catch(()=>undefined)},[]);
 const cargar=useCallback(async()=>{setLoading(true);try{const opts={limite:300,categoria:categoria??undefined};setServicios(texto.trim()?await buscarServicios(texto,opts):await listarServicios(opts));}catch(e){Alert.alert('Tarifario',e instanceof Error?e.message:String(e));}finally{setLoading(false)}},[texto,categoria]);
 useEffect(()=>{cargarCategorias()},[cargarCategorias]); useEffect(()=>{const t=setTimeout(()=>void cargar(),220);return()=>clearTimeout(t)},[cargar]);
 function abrirNuevo(){setForm(vacio());setFormOpen(true)}
 function editar(s:Servicio){setForm({id:s.id,codigoServicio:s.codigoServicio,nombreServicio:s.nombreServicio,categoria:s.categoria,precioBase:String(s.precioBase),unidad:s.unidad??'',tiempoEstimado:s.tiempoEstimado?String(s.tiempoEstimado):'',cantidadTecnicos:String(s.cantidadTecnicos||1)});setAccion(null);setFormOpen(true)}
 function tocar(s:Servicio){const now=Date.now();const doble=lastTap.current.id===s.id&&now-lastTap.current.at<330;if(tapTimer.current){clearTimeout(tapTimer.current);tapTimer.current=null;}lastTap.current={id:s.id,at:now};if(doble){setAccion(s);lastTap.current={id:-1,at:0};return}tapTimer.current=setTimeout(()=>{setSelected(v=>v.some(x=>x.id===s.id)?v.filter(x=>x.id!==s.id):[...v,s]);tapTimer.current=null;},340)}
 async function guardar(){if(!form.codigoServicio.trim()||!form.nombreServicio.trim()||!form.categoria.trim())return;setBusy(true);try{const d={codigoServicio:form.codigoServicio.trim(),nombreServicio:form.nombreServicio.trim(),categoria:form.categoria.trim(),precioBase:Number(form.precioBase)||0,precioTecnico:0,unidad:form.unidad||null,tiempoEstimado:form.tiempoEstimado?Number(form.tiempoEstimado):null,cantidadTecnicos:Number(form.cantidadTecnicos)||1,descripcionTecnica:null,detalleFactura:null,idPropietario:null,insumosCUP:null};if(form.id)await actualizarServicio(form.id,d);else await crearServicio(d);setFormOpen(false);await cargar();cargarCategorias()}catch(e){Alert.alert('No se pudo guardar',e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function confirmarEliminar(s:Servicio){setAccion(null);Alert.alert('Eliminar servicio',`¿Dar de baja “${s.nombreServicio}”?`,[{text:'Cancelar',style:'cancel'},{text:'Eliminar',style:'destructive',onPress:async()=>{try{await eliminarServicio(s.id);setSelected(v=>v.filter(x=>x.id!==s.id));await cargar()}catch(e){Alert.alert('Error',e instanceof Error?e.message:String(e))}}}])}
 function confirmarReemplazar(){Alert.alert('Reemplazar tarifario','Esto BORRA todos los servicios actuales y los cambia por los del archivo que elijas. No toca técnicos, órdenes ni configuración — solo el tarifario. ¿Seguro?',[{text:'Cancelar',style:'cancel'},{text:'Sí, reemplazar',style:'destructive',onPress:async()=>{setBusy(true);try{const r=await reemplazarTarifarioJSON();if(r.reemplazado&&r.resultado)Alert.alert('Listo',`Tarifario reemplazado: ${r.resultado.importados} servicios cargados.`);await cargar();cargarCategorias()}catch(e){Alert.alert('Error',e instanceof Error?e.message:String(e))}finally{setBusy(false)}}}])}
 function anadirOrden(){const items=selected;if(!items.length)return;agregarSeleccionTarifario(items);setSelected([]);router.push('/orden-nueva');}
 const total=selected.reduce((a,s)=>a+s.precioBase,0);
 return <SafeAreaView style={styles.flex} edges={['top']}><ThemedView style={styles.flex}>
  <View style={[styles.header,{alignItems:'flex-start'}]}><View><ThemedText type="title" style={styles.title}>Tarifario</ThemedText><ThemedText themeColor="textSecondary">Toca una vez para seleccionar · dos veces para acciones</ThemedText></View><Pressable onPress={abrirNuevo}><ThemedView type="primary" style={styles.newBtn}><ThemedText style={[styles.white,styles.newBtnIcon]}>+</ThemedText></ThemedView></Pressable></View>
  {selected.length>0&&<ThemedView type="primary" style={styles.selection}><Pressable onPress={()=>setSelected([])} style={styles.selectionClose} hitSlop={10}><ThemedText style={[styles.white,styles.selectionCloseIcon]}>×</ThemedText></Pressable><ThemedText style={[styles.white,styles.selectionTitle]}>{selected.length} servicio{selected.length===1?'':'s'} seleccionado{selected.length===1?'':'s'}</ThemedText><ThemedText style={styles.white}>{money(total)}</ThemedText><View style={styles.selectionBtns}><Pressable onPress={anadirOrden} style={[styles.addBtn,{flex:1}]}><ThemedText style={[styles.addBtnTxt,{color:theme.primary}]}>Añadir a Orden de Servicio</ThemedText></Pressable><Pressable onPress={()=>setSelected([])} style={[styles.cancelBtn,{flex:1}]}><ThemedText style={[styles.white,styles.cancelBtnTxt]}>Cancelar</ThemedText></Pressable></View></ThemedView>}
  <View style={styles.searchRow}><View style={[styles.searchWrap,{borderColor:theme.border,backgroundColor:theme.surface}]}><TextInput value={texto} onChangeText={setTexto} placeholder="Buscar por código, nombre o descripción…" placeholderTextColor={theme.textMuted} style={[styles.searchInput,{color:theme.text}]}/><Ionicons name="search-outline" size={16} color={theme.textMuted}/></View></View>
  <View style={styles.actionsRow}><Pressable onPress={async()=>{setBusy(true);try{await exportarTarifarioJSON()}catch(e){Alert.alert('Error',String(e))}finally{setBusy(false)}}} style={[styles.tool,{borderColor:theme.border}]}><ThemedText type="small">Exportar</ThemedText></Pressable><Pressable onPress={async()=>{setBusy(true);try{await importarTarifarioJSON();await cargar();cargarCategorias()}catch(e){Alert.alert('Error',String(e))}finally{setBusy(false)}}} style={[styles.tool,{borderColor:theme.border}]}><ThemedText type="small">Importar</ThemedText></Pressable><Pressable onPress={confirmarReemplazar} style={[styles.tool,{borderColor:theme.danger}]}><ThemedText type="small" style={{color:theme.danger}}>Reemplazar</ThemedText></Pressable></View>
  <FlatList horizontal data={categorias} keyExtractor={x=>x.categoria} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips} renderItem={({item})=><Pressable onPress={()=>setCategoria(categoria===item.categoria?null:item.categoria)}><View style={[styles.chip,{borderColor:theme.border,backgroundColor:categoria===item.categoria?theme.primary:theme.surface}]}><ThemedText type="small" numberOfLines={1} style={{color:categoria===item.categoria?'#fff':theme.textSecondary}}>{item.categoria} · {item.total}</ThemedText></View></Pressable>}/>
  {loading?<View style={styles.center}><ActivityIndicator color={theme.primary}/></View>:<FlatList data={servicios} keyExtractor={x=>String(x.id)} contentContainerStyle={styles.list} renderItem={({item})=>{const sel=selected.some(x=>x.id===item.id);return <Pressable onPress={()=>tocar(item)}><ThemedView type="surface" style={[styles.row,{borderColor:sel?theme.primary:theme.border,backgroundColor:sel?theme.backgroundSelected:theme.surface}]}><View style={styles.check}><ThemedText style={{color:sel?theme.primary:theme.textMuted,fontSize:18}}>{sel?'✓':'○'}</ThemedText></View><View style={{flex:1}}><ThemedText type="smallBold">{item.nombreServicio}</ThemedText><ThemedText type="small" themeColor="textSecondary">{item.codigoServicio} · {item.categoria}</ThemedText></View><ThemedText type="smallBold" style={{color:theme.primary}}>{money(item.precioBase)}</ThemedText></ThemedView></Pressable>}} ListEmptyComponent={<View style={styles.center}><ThemedText themeColor="textSecondary">No hay servicios que coincidan.</ThemedText></View>}/>}
  <Modal visible={!!accion} transparent animationType="fade" onRequestClose={()=>setAccion(null)}><View style={styles.modalBackdrop}><ThemedView type="surface" style={[styles.modal,{borderColor:theme.border}]}><ThemedText type="smallBold">{accion?.nombreServicio}</ThemedText><ThemedText type="small" themeColor="textSecondary">{accion?.codigoServicio}</ThemedText><Pressable onPress={()=>accion&&editar(accion)} style={styles.modalBtn}><ThemedText style={{color:theme.primary,fontWeight:'700'}}>✏ Editar</ThemedText></Pressable><Pressable onPress={()=>accion&&confirmarEliminar(accion)} style={styles.modalBtn}><ThemedText style={{color:theme.danger,fontWeight:'700'}}>🗑 Eliminar</ThemedText></Pressable><Pressable onPress={()=>setAccion(null)} style={styles.modalBtn}><ThemedText themeColor="textSecondary">Cancelar</ThemedText></Pressable></ThemedView></View></Modal>
  <Modal visible={formOpen} transparent animationType="slide" onRequestClose={()=>setFormOpen(false)}><View style={styles.modalBackdrop}><ScrollForm form={form} setForm={setForm} onSave={guardar} onCancel={()=>setFormOpen(false)} busy={busy}/></View></Modal>
 </ThemedView></SafeAreaView>
}
function CampoServicio({label,value,onChangeText,theme}:{label:string;value:string;onChangeText:(v:string)=>void;theme:ReturnType<typeof useTheme>}){return <View style={{gap:4}}><ThemedText type="small" themeColor="textSecondary">{label}</ThemedText><TextInput value={value} onChangeText={onChangeText} style={[styles.input,{color:theme.text,borderColor:theme.border,backgroundColor:theme.surface}]} /></View>}
function ScrollForm({form,setForm,onSave,onCancel,busy}:{form:ReturnType<typeof vacio>;setForm:Dispatch<SetStateAction<ReturnType<typeof vacio>>>;onSave:()=>void;onCancel:()=>void;busy:boolean}){const theme=useTheme();const campo=(k:keyof ReturnType<typeof vacio>)=>(v:string)=>setForm(p=>({...p,[k]:v}));return <ThemedView type="surface" style={styles.form}><ThemedText type="title" style={{fontSize:20}}>{form.id?'Editar servicio':'Nuevo servicio'}</ThemedText><CampoServicio label="Código" value={form.codigoServicio} onChangeText={campo('codigoServicio')} theme={theme}/><CampoServicio label="Nombre" value={form.nombreServicio} onChangeText={campo('nombreServicio')} theme={theme}/><CampoServicio label="Categoría" value={form.categoria} onChangeText={campo('categoria')} theme={theme}/><CampoServicio label="Precio base CUP" value={form.precioBase} onChangeText={campo('precioBase')} theme={theme}/><CampoServicio label="Unidad" value={form.unidad} onChangeText={campo('unidad')} theme={theme}/><CampoServicio label="Tiempo estimado (min)" value={form.tiempoEstimado} onChangeText={campo('tiempoEstimado')} theme={theme}/><CampoServicio label="Cantidad de técnicos" value={form.cantidadTecnicos} onChangeText={campo('cantidadTecnicos')} theme={theme}/><View style={styles.formBtns}><Pressable onPress={onCancel}><ThemedText themeColor="textSecondary">Cancelar</ThemedText></Pressable><Pressable onPress={onSave} disabled={busy}><ThemedView type="primary" style={styles.smallBtn}><ThemedText style={styles.white}>{busy?'Guardando…':'Guardar'}</ThemedText></ThemedView></Pressable></View></ThemedView>}
const styles=StyleSheet.create({flex:{flex:1},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:Spacing.four,paddingBottom:Spacing.two},title:{fontSize:28},newBtn:{width:40,height:40,borderRadius:10,alignItems:'center',justifyContent:'center'},newBtnIcon:{fontSize:22,lineHeight:24},white:{color:'#fff',fontWeight:'700'},selection:{marginHorizontal:Spacing.four,marginBottom:Spacing.two,padding:14,paddingTop:12,borderRadius:10,gap:4},selectionClose:{position:'absolute',top:8,right:10,zIndex:1,padding:4},selectionCloseIcon:{fontSize:20,lineHeight:22},selectionTitle:{paddingRight:26,fontWeight:'700'},selectionBtns:{flexDirection:'row',gap:8,marginTop:6},addBtn:{backgroundColor:'#fff',paddingVertical:10,borderRadius:8,alignItems:'center'},addBtnTxt:{fontWeight:'800'},cancelBtn:{borderWidth:1.5,borderColor:'#fff',paddingVertical:10,borderRadius:8,alignItems:'center'},cancelBtnTxt:{fontWeight:'700'},searchRow:{paddingHorizontal:Spacing.four,paddingBottom:8},searchWrap:{flexDirection:'row',alignItems:'center',borderWidth:1,borderRadius:8,paddingLeft:12,paddingRight:10},searchInput:{flex:1,paddingVertical:9,paddingRight:8},searchIcon:{fontSize:16},actionsRow:{paddingHorizontal:Spacing.four,paddingBottom:10,flexDirection:'row',gap:8},tool:{borderWidth:1,borderRadius:8,paddingHorizontal:10,paddingVertical:9},chips:{gap:8,paddingHorizontal:Spacing.four,paddingVertical:10},chip:{borderWidth:1,borderRadius:999,paddingHorizontal:10,paddingVertical:6,maxWidth:220},list:{paddingHorizontal:Spacing.four,paddingBottom:Spacing.six,gap:8},row:{padding:14,borderRadius:10,borderWidth:1,flexDirection:'row',alignItems:'center',gap:10},check:{width:26,alignItems:'center'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:30},modalBackdrop:{flex:1,backgroundColor:'rgba(0,0,0,.45)',justifyContent:'center',padding:20},modal:{padding:18,borderRadius:14,borderWidth:1,gap:10},modalBtn:{paddingVertical:12},form:{maxHeight:'90%',padding:18,borderRadius:14,gap:10},input:{borderWidth:1,borderRadius:8,paddingHorizontal:10,paddingVertical:9},formBtns:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:20,marginTop:8},smallBtn:{paddingHorizontal:14,paddingVertical:10,borderRadius:8}});
